services:
  users-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"

volumes:
  users_db_data:
